---
# Receive dispatch events from LizardByte repositories that have Qodana config files.

name: Qodana Scan

on:
  repository_dispatch:
    types: [qodana-scan]

concurrency:
  # ensure only one workflow runs for a given repo and ref, cancel in progress to only run the latest
  group: ${{ github.event.client_payload.github.repository }}-${{ github.event.client_payload.github.workflow }}- ${{ github.event.client_payload.github.ref }}  # yamllint disable-line rule:line-length
  cancel-in-progress: true

jobs:
  initialize-notify:
    name: Initialize Notify
    if: ${{ startsWith(github.event.client_payload.github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup client payload
        id: client_payload
        run: |
          workflow_url_a=https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
          workflow_url=${workflow_url_a}/actions/runs/${{ github.run_id }}

          client_payload=$(echo '{
            "final": "'"false"'",
            "pull_request_number": "'"${{ github.event.client_payload.github.event.number }}"'",
            "workflow_url": "'"${workflow_url}"'"
          }' | jq -c .)

          echo $client_payload
          echo $client_payload | jq .
          echo "client_payload=$client_payload" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ github.event.client_payload.github.event.repository.name }}
          event-type: qodana-notify
          client-payload: ${{ steps.client_payload.outputs.client_payload }}

  qodana:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(github.event.client_payload.matrix) }}
      max-parallel: 1
    name: Qodana-Scan-${{ matrix.language }}
    steps:
      - name: Queue
        # we only want to run one add job at a time, so queue them
        uses: ahmadnassri/action-workflow-queue@v1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.checkout_repo }}
          ref: ${{ github.event.client_payload.checkout_ref }}
          submodules: recursive

      - name: Checkout Qodana/gh-pages repo
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of the personal token
          fetch-depth: 0  # otherwise, will fail to push refs to dest repo

      - name: Get baseline
        id: baseline
        run: |
          sarif_file=qodana.sarif.json
          repo=${{ github.event.client_payload.github.event.repository.name }}
          target=${{ github.event.client_payload.target }}
          language=${{ matrix.language }}

          baseline_file="./gh-pages/${repo}/${target}/${language}/results/${sarif_file}"

          # check if file exists
          if [ -f ${baseline_file} ]
          then
              echo "baseline exists"
              echo "baseline_args=--baseline,qodana.sarif.json" >> $GITHUB_OUTPUT

              # copy the file
              cp -f ${baseline_file} ./${sarif_file}
          else
              echo "baseline does not exist"
              echo "baseline_args=" >> $GITHUB_OUTPUT
          fi

      - name: Rename Qodana config file
        id: rename
        run: |
          # rename the file
          if [ "${{ matrix.file }}" != "./qodana.yaml" ]
          then
            mv -f ${{ matrix.file }} ./qodana.yaml
          fi

      - name: Qodana
        id: qodana
        if: ${{ steps.rename.conclusion == 'success' }}
        continue-on-error: true
        uses: JetBrains/qodana-action@v2022.3.4
        with:
          additional-cache-hash: ${{ github.event.client_payload.checkout_repo }}-${{ github.event.client_payload.checkout_ref }}-${{ github.event.client_payload.destination}}-${{ matrix.language }}  # yamllint disable-line rule:line-length
          args: '--print-problems,${{ steps.baseline.outputs.baseline_args }}'
          pr-mode: false
          upload-result: true
          use-caches: true

      - name: Prepare gh-pages
        id: pages
        if: ${{ steps.qodana.conclusion != 'skipped' }}
        continue-on-error: true
        run: |
          repo=${{ github.event.client_payload.github.event.repository.name }}
          destination=${{ github.event.client_payload.destination }}
          language=${{ matrix.language }}

          # set the output directory
          output_dir=./gh-pages/${repo}/${destination}/${language}
          mkdir -p $output_dir

          # empty contents
          rm -f -r $output_dir/*

          # copy qodana results
          cp -f -r ${{ runner.temp }}/qodana/results/report/. $output_dir/

      - name: Deploy to gh-pages
        id: deploy
        if: ${{ steps.pages.conclusion == 'success' }}
        continue-on-error: true
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          author_email: ${{ secrets.GH_BOT_EMAIL }}
          author_name: ${{ secrets.GH_BOT_NAME }}
          directory: gh-pages
          branch: gh-pages
          force: false
          message: >-
            update
            ${{ github.event.client_payload.github.event.repository.name }}
            ${{ github.event.client_payload.destination }}
            ${{ matrix.language }}

  final-notify:
    name: Final Notify
    needs: [initialize-notify, qodana]
    if: ${{ startsWith(github.event.client_payload.github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup client payload
        id: client_payload
        run: |
          workflow_url_a=https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
          workflow_url=${workflow_url_a}/actions/runs/${{ github.run_id }}

          client_payload=$(echo '{
            "final": "'"true"'",
            "pull_request_number": "'"${{ github.event.client_payload.github.event.number }}"'",
            "reports_markdown": "'"${{ github.event.client_payload.reports_markdown }}"'",
            "status": "'"${{ needs.qodana.result }}"'",
            "workflow_url": "'"${workflow_url}"'"
          }' | jq -c .)

          echo $client_payload
          echo $client_payload | jq .
          echo "client_payload=$client_payload" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ github.event.client_payload.github.event.repository.name }}
          event-type: qodana-notify
          client-payload: ${{ steps.client_payload.outputs.client_payload }}
